image: node:latest

stages:
    - build
    - deploy
    
build:
    stage: build
    script:
        - echo "Building deploy package"
        - yarn install
        - yarn build
        - echo "Build successful"