image: node:latest

variables:
    DOCKER_TLS_CERTDIR: ""

stages:
    - build
    - test
    - docker-build
    - deploy

yarn-build:
    stage: build
    script:
        - echo "Building deploy package"
        - yarn install
        - yarn build
        - echo "Build successful"
    cache:
        paths:
            - node_modules
    artifacts:
        paths:
            - build

yarn-test:
    stage: test
    script:
        - echo "Tests not implemented"

docker-dev-build:
    only:
        - manual
    image: docker:19.03.1-dind
    stage: docker-build
    tags:
        - docker
    script:
        - cd docker/dev
        - docker build -t dev-webapp .
